# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=32)),
                ('link', models.URLField()),
            ],
        ),
    ]
