# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oday',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
