# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_bobao360'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobao360',
            name='time',
            field=models.DateField(),
        ),
    ]
