# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_auto_20170308_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=128, unique=True)),
                ('bug_id', models.CharField(default='', max_length=128)),
                ('bug_time', models.DateField()),
                ('bug_url', models.URLField()),
                ('bug_platform', models.CharField(default='', max_length=128)),
                ('bug_type', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Security_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=128, unique=True)),
                ('event_time', models.DateField()),
                ('event_url', models.URLField()),
                ('event_platform', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
