# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbs_user',
            name='user',
        ),
    ]
