# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0001_initial'),
        ('app01', '0002_remove_bbs_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs_user',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='logReg.User'),
            preserve_default=False,
        ),
    ]
