# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20170326_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_user',
            name='photo',
            field=models.ImageField(default='static/images/user.png', upload_to='/static/images/'),
        ),
    ]
