# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170116_1737'),
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
